---

- name: packages
  yum: >
    name={{ item }}
    state=present
  with_items:
    - http://dl.iuscommunity.org/pub/ius/stable/CentOS/6/x86_64/ius-release-1.0-11.ius.centos6.noarch.rpm
  sudo: yes
