---

- name: packages
  yum: >
    name={{ item }}
    state=present
  with_items:
    - zsh
  sudo: yes

- name: clone
  git: >
    repo=https://github.com/robbyrussell/oh-my-zsh.git
    dest=/home/{{ user }}/.oh-my-zsh
    update=no
  sudo: no

- name: template
  shell: >
    cp /home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{ user }}/.zshrc
    creates=/home/{{ user }}/.zshrc
  sudo: no

- name: plugins
  lineinfile: >
    dest=/home/{{ user }}/.zshrc
    line="plugins=(composer symfony2 history history-substring-search)"
    regexp="plugins=\(.*\)"

- name: prompt
  lineinfile: >
    dest=/home/{{ user }}/.zshrc
    line="PROMPT='%{$fg[cyan]%}%n%{$fg[red]%}@%{$fg[cyan]%}%m %{$fg_bold[red]%}âžœ %{$fg_bold[green]%}%p %{$fg[cyan]%}%c %{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'"
    regexp="^PROMPT="

- name: shell
  user: >
    name={{ user }}
    shell=/bin/zsh
