---

- name: packages
  apt: >
      pkg={{ item }}
      state=present
  with_items:
      - mysql-server
  sudo: yes

- name: service
  service: >
      name=mysql
      state=started
      enabled=yes
