---

- name: package
  apt: >
      pkg=apache2-mpm-prefork
      state=present

- name: disable default
  shell: >
      a2dissite default
      removes=/etc/apache2/sites-enabled/000-default
  notify: apache restart

- name: service
  service: >
      name=apache2
      state=started
      enabled=yes
