---

- name: config template
  template: >
    src=config.j2
    dest=/home/{{ user }}/.ssh/config
  sudo: no

- name: sudoers template
  template: >
      src=sudoers.j2
      dest=/etc/sudoers.d/ssh
  sudo: yes

- name: sudoers file
  file: >
      path=/etc/sudoers.d/ssh
      state=file
      owner=root
      group=root
  sudo: yes
