---

- name: repositories
  apt_repository: >
      repo="{{ item }}"
      state=present
      update_cache=yes
  with_items:
      - deb http://debian.proxad.net/debian wheezy-backports main
  sudo: yes
