---

#########
# Nginx #
#########

_env_nginx_configs:
  # PhpMyAdmin
  - file:     phpmyadmin.conf
    template: configs/server_{{ _env }}.conf.j2
    config:
      - listen: 1979
      - root:   "{{ elao_phpmyadmin_dir }}"
      - include: conf.d/gzip
      - client_max_body_size: 16M
      - location /:
        - try_files: $uri /index.php$is_args$args
      - location ~ ^/.+\.php(/|$):
        - include: conf.d/php_fpm_params
  # PhpPgAdmin
  #- file:     phppgadmin.conf
  #  template: configs/server_{{ _env }}.conf.j2
  #  config:
  #    - listen: 1980
  #    - root:   "{{ elao_phppgadmin_dir }}"
  #    - include: conf.d/gzip
  #    - client_max_body_size: 16M
  #    - location /:
  #      - try_files: $uri /index.php$is_args$args
  #    - location ~ ^/.+\.php(/|$):
  #      - include: conf.d/php_fpm_params
  # PhpRedisAdmin
  #- file:     phpredisadmin.conf
  #  template: configs/server_{{ _env }}.conf.j2
  #  config:
  #    - listen: 1981
  #    - root:   "{{ elao_phpredisadmin_dir }}"
  #    - include: conf.d/gzip
  #    - client_max_body_size: 16M
  #    - location /:
  #      - try_files: $uri /index.php$is_args$args
  #    - location ~ ^/.+\.php(/|$):
  #      - include: conf.d/php_fpm_params
