---

- name: packages
  yum: >
    name={{ item }}
    state=present
  with_items:
    - vim
  sudo: yes


- name: rc template
  template: >
      src=rc.j2
      dest=/home/{{ user }}/.vimrc
  sudo: no
