---

- hosts: all
  sudo:  yes

  vars:
    _env_dev: "{{ 'env_dev' in group_names }}"
    _user:    "{{ 'vagrant' if 'env_dev' in group_names else 'docker' }}"

  roles:
    - { role: elao.motd }
    - { role: elao.timezone }
    - { role: elao.env }
    - { role: elao.apt }
    - { role: elao.ssh }
    - { role: elao.git }
    - { role: elao.zsh, when: _env_dev }
    - { role: elao.ohmyzsh, when: _env_dev }
    - { role: elao.curl }
    - { role: elao.acl }
    - { role: elao.files }
    - { role: elao.make }
    - { role: elao.nodejs }
    - { role: elao.npm }
    - { role: elao.ruby }
    - { role: elao.gem }
    - { role: elao.phantomjs }
    - { role: elao.mailcatcher }
    - { role: elao.logio, when: _env_dev }
    - { role: elao.php }
    - { role: elao.composer }
    - { role: elao.nginx,
        elao_nginx_configs: "{{ _nginx_configs + _env_nginx_configs|default([]) }}"
      }
    # Cron
    #- { role: elao.cron, when: _env_dev }
    # Python
    #- { role: elao.python }
    #- { role: elao.pip }
    # Supervisor (need python)
    #- { role: elao.supervisor }
    # MySql
    - { role: elao.mysql }
    - { role: elao.phpmyadmin, when: _env_dev }
    # PostgreSQL
    #- { role: elao.postgresql }
    #- { role: elao.phppgadmin, when: _env_dev }
    # Redis
    #- { role: elao.redis }
    #- { role: elao.phpredisadmin, when: _env_dev }
    # Elasticsearch
    #- { role: elao.java }
    #- { role: elao.elasticsearch }
    # MongoDB
    #- { role: elao.mongodb }
    # App
