- src:     https://github.com/ElaoInfra/ansible-role-motd
  name:    elao.motd
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-timezone
  name:    elao.timezone
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-env
  name:    elao.env
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-apt
  name:    elao.apt
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-ssh
  name:    elao.ssh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-git
  name:    elao.git
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-zsh
  name:    elao.zsh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-ohmyzsh
  name:    elao.ohmyzsh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-curl
  name:    elao.curl
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-acl
  name:    elao.acl
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-files
  name:    elao.files
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-make
  name:    elao.make
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-nodejs
  name:    elao.nodejs
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-npm
  name:    elao.npm
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-ruby
  name:    elao.ruby
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-gem
  name:    elao.gem
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-phantomjs
  name:    elao.phantomjs
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-mailcatcher
  name:    elao.mailcatcher
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-logio
  name:    elao.logio
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-php
  name:    elao.php
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-composer
  name:    elao.composer
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-nginx
  name:    elao.nginx
  version: origin/1.0

# Cron

- src:     https://github.com/ElaoInfra/ansible-role-cron
  name:    elao.cron
  version: origin/1.0

# Python

- src:     https://github.com/ElaoInfra/ansible-role-python
  name:    elao.python
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-pip
  name:    elao.pip
  version: origin/1.0

# Supervisor

- src:     https://github.com/ElaoInfra/ansible-role-supervisor
  name:    elao.supervisor
  version: origin/1.0

# MySQL

- src:     https://github.com/ElaoInfra/ansible-role-mysql
  name:    elao.mysql
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-phpmyadmin
  name:    elao.phpmyadmin
  version: origin/1.0

# PostgreSQL

- src:     https://github.com/ElaoInfra/ansible-role-postgresql
  name:    elao.postgresql
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-phppgadmin
  name:    elao.phppgadmin
  version: origin/1.0

# Redis

- src:     https://github.com/ElaoInfra/ansible-role-redis
  name:    elao.redis
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-phpredisadmin
  name:    elao.phpredisadmin
  version: origin/1.0

# Elasticsearch

- src:     https://github.com/ElaoInfra/ansible-role-java
  name:    elao.java
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-elasticsearch
  name:    elao.elasticsearch
  version: origin/1.0

# MongoDB

- src:     https://github.com/ElaoInfra/ansible-role-mongodb
  name:    elao.mongodb
  version: origin/1.0

# App
